'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog'
import { DataTable, Column } from '@/components/ui/data-table'
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu'
import {
  BarChart3,
  Search,
  FileDown,
  Eye,
  Building2,
  FileText,
  FileCode,
  FileType,
  Braces,
  Code2,
} from 'lucide-react'
import {
  downloadReport,
  FORMAT_OPTIONS,
  type DownloadFormat,
  type ReportDownloadData,
} from '@/lib/report-download'

interface Report {
  id: string
  vendorId: string | null
  reportType: string
  reportName: string
  generatedBy: string | null
  generatedDate: string
  content: string | null
  status: string
  approvedBy: string | null
  approvedDate: string | null
  createdAt: string
  vendor: { id: string; name: string } | null
}

const statusVariant = (s: string) => {
  switch (s) {
    case 'PUBLISHED': case 'APPROVED': return 'low'
    case 'GENERATED': return 'info'
    case 'PENDING_APPROVAL': return 'medium'
    case 'DRAFT': return 'secondary'
    default: return 'secondary'
  }
}

const typeLabel = (t: string) =>
  t.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())

const FORMAT_ICONS: Record<DownloadFormat, React.ReactNode> = {
  pdf: <FileText className="h-4 w-4" />,
  docx: <FileType className="h-4 w-4" />,
  md: <FileCode className="h-4 w-4" />,
  json: <Braces className="h-4 w-4" />,
  xml: <Code2 className="h-4 w-4" />,
}

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [selectedReport, setSelectedReport] = useState<Report | null>(null)

  // Download modal state
  const [downloadTarget, setDownloadTarget] = useState<Report | null>(null)
  const [downloadFormat, setDownloadFormat] = useState<DownloadFormat>('pdf')
  const [downloadFilename, setDownloadFilename] = useState('')
  const [downloading, setDownloading] = useState(false)

  useEffect(() => {
    fetch('/api/reports')
      .then((r) => r.json())
      .then((data) => setReports(Array.isArray(data) ? data : []))
      .catch(() => setReports([]))
      .finally(() => setLoading(false))
  }, [])

  const filtered = reports.filter((r) =>
    !search ||
    r.reportName.toLowerCase().includes(search.toLowerCase()) ||
    r.reportType.toLowerCase().includes(search.toLowerCase()) ||
    r.vendor?.name.toLowerCase().includes(search.toLowerCase())
  )

  /** Open the download modal for a report + format. */
  const openDownloadModal = (report: Report, format: DownloadFormat) => {
    setDownloadTarget(report)
    setDownloadFormat(format)
    setDownloadFilename(report.reportName)
  }

  /** Execute the download. */
  const handleDownload = async () => {
    if (!downloadTarget || !downloadTarget.content) return
    setDownloading(true)
    try {
      const data: ReportDownloadData = {
        reportName: downloadTarget.reportName,
        reportType: downloadTarget.reportType,
        content: downloadTarget.content,
        vendorName: downloadTarget.vendor?.name,
        generatedBy: downloadTarget.generatedBy || undefined,
        generatedDate: downloadTarget.generatedDate,
        status: downloadTarget.status,
      }
      await downloadReport(data, downloadFormat, downloadFilename || downloadTarget.reportName)
    } finally {
      setDownloading(false)
      setDownloadTarget(null)
    }
  }

  const columns: Column<Report>[] = [
    {
      key: 'reportName',
      header: 'Report',
      sortable: true,
      render: (row) => (
        <div>
          <div className="font-medium">{row.reportName}</div>
          <div className="text-xs text-gray-500">{typeLabel(row.reportType)}</div>
        </div>
      ),
    },
    {
      key: 'vendor.name',
      header: 'Vendor',
      sortable: true,
      render: (row) =>
        row.vendor ? (
          <div className="flex items-center gap-2">
            <Building2 className="h-4 w-4 text-gray-400" />
            <span>{row.vendor.name}</span>
          </div>
        ) : (
          <span className="text-gray-500">Portfolio-wide</span>
        ),
    },
    {
      key: 'status',
      header: 'Status',
      sortable: true,
      render: (row) => (
        <Badge variant={statusVariant(row.status)}>{row.status.replace(/_/g, ' ')}</Badge>
      ),
    },
    {
      key: 'generatedBy',
      header: 'Generated By',
      render: (row) =>
        row.generatedBy ? (
          <Badge variant="outline">{row.generatedBy}</Badge>
        ) : (
          <span className="text-gray-400">&mdash;</span>
        ),
    },
    {
      key: 'generatedDate',
      header: 'Date',
      sortable: true,
      render: (row) => new Date(row.generatedDate).toLocaleDateString(),
    },
    {
      key: 'actions',
      header: '',
      className: 'text-right',
      render: (row) => (
        <div className="flex items-center justify-end gap-1">
          <Button
            variant="ghost"
            size="sm"
            onClick={(e) => {
              e.stopPropagation()
              setSelectedReport(row)
            }}
          >
            <Eye className="h-4 w-4 mr-1" />
            View
          </Button>

          {/* Download dropdown */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="sm"
                disabled={!row.content}
                onClick={(e) => e.stopPropagation()}
              >
                <FileDown className="h-4 w-4 mr-1" />
                Download
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>Export Format</DropdownMenuLabel>
              <DropdownMenuSeparator />
              {FORMAT_OPTIONS.map((fmt) => (
                <DropdownMenuItem
                  key={fmt.value}
                  onClick={(e) => {
                    e.stopPropagation()
                    openDownloadModal(row, fmt.value)
                  }}
                >
                  {FORMAT_ICONS[fmt.value]}
                  <span>{fmt.label}</span>
                  <span className="ml-auto text-xs text-muted-foreground">{fmt.ext}</span>
                </DropdownMenuItem>
              ))}
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      ),
    },
  ]

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
          <p className="text-sm text-gray-500">
            AI-generated risk reports and executive summaries
          </p>
        </div>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center gap-3">
            <div className="relative flex-1 max-w-sm">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
              <Input
                placeholder="Search reports..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="pl-9"
              />
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <DataTable
            columns={columns}
            data={filtered}
            loading={loading}
            emptyIcon={<BarChart3 className="h-12 w-12 text-gray-300 mb-3" />}
            emptyTitle="No reports yet"
            emptyDescription="Reports will appear here when generated by RITA."
          />
        </CardContent>
      </Card>

      {/* ── Report View Dialog ── */}
      <Dialog open={!!selectedReport} onOpenChange={() => setSelectedReport(null)}>
        <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
          {selectedReport && (
            <>
              <DialogHeader>
                <DialogTitle>{selectedReport.reportName}</DialogTitle>
                <div className="flex items-center gap-2 pt-1">
                  <Badge variant={statusVariant(selectedReport.status)}>
                    {selectedReport.status.replace(/_/g, ' ')}
                  </Badge>
                  <span className="text-sm text-gray-500">
                    {typeLabel(selectedReport.reportType)}
                  </span>
                  {selectedReport.vendor && (
                    <span className="text-sm text-gray-500">
                      &middot; {selectedReport.vendor.name}
                    </span>
                  )}
                </div>
              </DialogHeader>

              {/* Download bar inside view dialog */}
              {selectedReport.content && (
                <div className="flex items-center gap-2 py-2 px-3 bg-gray-50 rounded-lg border">
                  <FileDown className="h-4 w-4 text-gray-500 shrink-0" />
                  <span className="text-sm text-gray-600 shrink-0">Download as:</span>
                  <div className="flex items-center gap-1 flex-wrap">
                    {FORMAT_OPTIONS.map((fmt) => (
                      <Button
                        key={fmt.value}
                        variant="outline"
                        size="sm"
                        className="h-7 text-xs gap-1"
                        onClick={() => openDownloadModal(selectedReport, fmt.value)}
                      >
                        {FORMAT_ICONS[fmt.value]}
                        {fmt.label}
                      </Button>
                    ))}
                  </div>
                </div>
              )}

              <div className="prose prose-sm max-w-none mt-4">
                {selectedReport.content ? (
                  <div className="whitespace-pre-wrap font-mono text-sm bg-gray-50 p-4 rounded-lg">
                    {selectedReport.content}
                  </div>
                ) : (
                  <p className="text-gray-500 italic">No content available for this report.</p>
                )}
              </div>
              <div className="flex items-center justify-between mt-4 pt-4 border-t text-sm text-gray-500">
                <span>
                  Generated: {new Date(selectedReport.generatedDate).toLocaleDateString()}
                  {selectedReport.generatedBy && ` by ${selectedReport.generatedBy}`}
                </span>
                {selectedReport.approvedBy && (
                  <span>
                    Approved by {selectedReport.approvedBy} on{' '}
                    {new Date(selectedReport.approvedDate!).toLocaleDateString()}
                  </span>
                )}
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* ── Download Filename Modal ── */}
      <Dialog open={!!downloadTarget} onOpenChange={() => setDownloadTarget(null)}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Save Report</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-700">Filename</label>
              <div className="flex items-center gap-2">
                <Input
                  value={downloadFilename}
                  onChange={(e) => setDownloadFilename(e.target.value)}
                  placeholder="Enter filename..."
                  className="flex-1"
                />
                <span className="text-sm text-muted-foreground shrink-0">
                  {FORMAT_OPTIONS.find((f) => f.value === downloadFormat)?.ext}
                </span>
              </div>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-700">Format</label>
              <div className="grid grid-cols-5 gap-1">
                {FORMAT_OPTIONS.map((fmt) => (
                  <Button
                    key={fmt.value}
                    variant={downloadFormat === fmt.value ? 'default' : 'outline'}
                    size="sm"
                    className="text-xs gap-1"
                    onClick={() => setDownloadFormat(fmt.value)}
                  >
                    {FORMAT_ICONS[fmt.value]}
                    {fmt.ext}
                  </Button>
                ))}
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDownloadTarget(null)}>
              Cancel
            </Button>
            <Button onClick={handleDownload} disabled={downloading || !downloadFilename.trim()}>
              <FileDown className="h-4 w-4 mr-2" />
              {downloading ? 'Saving...' : 'Save'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
