'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DataTable, Column } from '@/components/ui/data-table'
import {
  BarChart3,
  Search,
  FileDown,
  Eye,
  Building2,
} from 'lucide-react'

interface Report {
  id: string
  vendorId: string | null
  reportType: string
  reportName: string
  generatedBy: string | null
  generatedDate: string
  content: string | null
  status: string
  approvedBy: string | null
  approvedDate: string | null
  createdAt: string
  vendor: { id: string; name: string } | null
}

const statusVariant = (s: string) => {
  switch (s) {
    case 'PUBLISHED': case 'APPROVED': return 'low'
    case 'GENERATED': return 'info'
    case 'PENDING_APPROVAL': return 'medium'
    case 'DRAFT': return 'secondary'
    default: return 'secondary'
  }
}

const typeLabel = (t: string) =>
  t.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [selectedReport, setSelectedReport] = useState<Report | null>(null)

  useEffect(() => {
    fetch('/api/reports')
      .then((r) => r.json())
      .then((data) => setReports(Array.isArray(data) ? data : []))
      .catch(() => setReports([]))
      .finally(() => setLoading(false))
  }, [])

  const filtered = reports.filter((r) =>
    !search ||
    r.reportName.toLowerCase().includes(search.toLowerCase()) ||
    r.reportType.toLowerCase().includes(search.toLowerCase()) ||
    r.vendor?.name.toLowerCase().includes(search.toLowerCase())
  )

  const columns: Column<Report>[] = [
    {
      key: 'reportName',
      header: 'Report',
      sortable: true,
      render: (row) => (
        <div>
          <div className="font-medium">{row.reportName}</div>
          <div className="text-xs text-gray-500">{typeLabel(row.reportType)}</div>
        </div>
      ),
    },
    {
      key: 'vendor.name',
      header: 'Vendor',
      sortable: true,
      render: (row) =>
        row.vendor ? (
          <div className="flex items-center gap-2">
            <Building2 className="h-4 w-4 text-gray-400" />
            <span>{row.vendor.name}</span>
          </div>
        ) : (
          <span className="text-gray-500">Portfolio-wide</span>
        ),
    },
    {
      key: 'status',
      header: 'Status',
      sortable: true,
      render: (row) => (
        <Badge variant={statusVariant(row.status)}>{row.status.replace(/_/g, ' ')}</Badge>
      ),
    },
    {
      key: 'generatedBy',
      header: 'Generated By',
      render: (row) =>
        row.generatedBy ? (
          <Badge variant="outline">{row.generatedBy}</Badge>
        ) : (
          <span className="text-gray-400">—</span>
        ),
    },
    {
      key: 'generatedDate',
      header: 'Date',
      sortable: true,
      render: (row) => new Date(row.generatedDate).toLocaleDateString(),
    },
    {
      key: 'actions',
      header: '',
      className: 'text-right',
      render: (row) => (
        <Button
          variant="ghost"
          size="sm"
          onClick={(e) => {
            e.stopPropagation()
            setSelectedReport(row)
          }}
        >
          <Eye className="h-4 w-4 mr-1" />
          View
        </Button>
      ),
    },
  ]

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
          <p className="text-sm text-gray-500">
            AI-generated risk reports and executive summaries
          </p>
        </div>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center gap-3">
            <div className="relative flex-1 max-w-sm">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
              <Input
                placeholder="Search reports..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="pl-9"
              />
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <DataTable
            columns={columns}
            data={filtered}
            loading={loading}
            emptyIcon={<BarChart3 className="h-12 w-12 text-gray-300 mb-3" />}
            emptyTitle="No reports yet"
            emptyDescription="Reports will appear here when generated by RITA."
          />
        </CardContent>
      </Card>

      {/* Report detail dialog */}
      <Dialog open={!!selectedReport} onOpenChange={() => setSelectedReport(null)}>
        <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
          {selectedReport && (
            <>
              <DialogHeader>
                <DialogTitle>{selectedReport.reportName}</DialogTitle>
                <div className="flex items-center gap-2 pt-1">
                  <Badge variant={statusVariant(selectedReport.status)}>
                    {selectedReport.status.replace(/_/g, ' ')}
                  </Badge>
                  <span className="text-sm text-gray-500">
                    {typeLabel(selectedReport.reportType)}
                  </span>
                  {selectedReport.vendor && (
                    <span className="text-sm text-gray-500">
                      &middot; {selectedReport.vendor.name}
                    </span>
                  )}
                </div>
              </DialogHeader>
              <div className="prose prose-sm max-w-none mt-4">
                {selectedReport.content ? (
                  <div className="whitespace-pre-wrap font-mono text-sm bg-gray-50 p-4 rounded-lg">
                    {selectedReport.content}
                  </div>
                ) : (
                  <p className="text-gray-500 italic">No content available for this report.</p>
                )}
              </div>
              <div className="flex items-center justify-between mt-4 pt-4 border-t text-sm text-gray-500">
                <span>
                  Generated: {new Date(selectedReport.generatedDate).toLocaleDateString()}
                  {selectedReport.generatedBy && ` by ${selectedReport.generatedBy}`}
                </span>
                {selectedReport.approvedBy && (
                  <span>
                    Approved by {selectedReport.approvedBy} on{' '}
                    {new Date(selectedReport.approvedDate!).toLocaleDateString()}
                  </span>
                )}
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}
